version: '3.8'
services:
  eshopdb:
    image: postgres

  seq:
    image: datalust/seq:latest

  distributedcache:
    image: redis:latest

volumes:
  postgres_eshopdb:







  # api:
  #   image: ${DOCKER_REGISTRY-}api
  #   build:
  #     context: .
  #     dockerfile: Bootstrapper/Api/Dockerfile
