version: '3.8'
services:
  postgres:
    image: postgres

  seq:
    image: datalust/seq:latest

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:management

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3

volumes:
  postgres_eshopdb:






  # api:
  #   image: ${DOCKER_REGISTRY-}api
  #   build:
  #     context: .
  #     dockerfile: Bootstrapper/Api/Dockerfile
