services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=eshopdb
      - POSTGRES_PASSWORD=eshopdb
      - POSTGRES_DB=eshopdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/

  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  seq:
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: true
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"

  rabbitmq:
    container_name: rabbitmq
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=eshopdb
      - RABBITMQ_DEFAULT_PASS=eshopdb
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  # make postgres create schema before using keycloak
  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=eshopdb
      - KEYCLOAK_ADMIN_PASSWORD=eshopdb
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/eshopdb?currentSchema=keycloak
      - KC_DB_USERNAME=eshopdb
      - KC_DB_PASSWORD=eshopdb
      - KC_HTTP_PORT=9090
      - KC_HOSTNAME=localhost
    restart: always
    ports:
      - "9090:9090"
    command:
      - start-dev
    depends_on:
      - postgres






#       - ASPNETCORE_HTTPS_PORTS=8081
#     ports:
#       - "8080"
#       - "8081"
#     volumes:
#       - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#       - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#       - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
#       - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
