services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=eshopdb
      - POSTGRES_PASSWORD=eshopdb
      - POSTGRES_DB=eshopdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/

  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  seq:
    container_name: seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: true
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"

  rabbitmq:
    container_name: rabbitmq
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=eshopdb
      - RABBITMQ_DEFAULT_PASS=eshopdb
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  # make postgres create schema before using keycloak
  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=eshopdb
      - KEYCLOAK_ADMIN_PASSWORD=eshopdb
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/eshopdb?currentSchema=keycloak
      - KC_DB_USERNAME=eshopdb
      - KC_DB_PASSWORD=eshopdb
      - KC_HTTP_PORT=9090
      - KC_HOSTNAME=localhost
    restart: always
    ports:
      - "9090:9090"
    command:
      - start-dev
    depends_on:
      - postgres

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=eshopdb;Port=5432;Database=eshopdb;User Id=eshopdb;Password=eshopdb;Include Error Detail=true
      - ConnectionStrings__Redis=redis:6379
      - MessageBroker__Host=amqp://rabbitmq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Keycloak__AuthServerUrl=http://keycloak:9090/
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__Using__1=Serilog.Sinks.Seq
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Information
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341
      - Serilog__Enrich__0=FromLogContext
      - Serilog__Enrich__1=WithMachineName
      - Serilog__Enrich__2=WithProcessId
      - Serilog__Enrich__3=WithThreadId
      - Serilog__Properties__Application=EShop ASP.NET Core App
      - Serilog__Properties__Environment=Development
    depends_on:
      - postgres
      - redis
      - seq
      - rabbitmq
      - keycloak
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
